name: oqyol
description: A Flutter MVVM with Riverpod and Google Maps example

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  flutter_compass: ^0.8.1
  flutter_local_notifications: ^18.0.1
  google_maps_flutter: ^2.2.5
  location: ^7.0.1
  shared_preferences: ^2.3.3
  google_mobile_ads: ^5.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/mmmarkers.json
    - assets/icons/0.png
    - assets/icons/1.png
    - assets/icons/2.png
    - assets/icons/car.png
    - assets/sounds/ru/0.mp3
    - assets/sounds/en/0.mp3
    - assets/sounds/0.mp3
    - assets/sounds/ru/1.mp3
    - assets/sounds/en/1.mp3
    - assets/sounds/1.mp3
    - assets/sounds/ru/2.mp3
    - assets/sounds/en/2.mp3
    - assets/sounds/2.mp3
    - assets/map/light.json
    - assets/map/dark.json
